name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: prod
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      -         
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - 
        name: Install dependencies
        run: npm install
      - 
        name: Test and coverage
        run: npm test -- --coverage
      - 
        name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deployment:
      runs-on: ubuntu-latest
      needs: [build, sonarcloud]
      steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        - 
          name: Deploy to Cloud Run
          id: deploy
          uses: google-github-actions/deploy-cloudrun@v2
          with:
            service: 'docker-nodejs-sample'
            image: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            flags: '--port=3000'
            region: 'us-central1'